name = "Autonorm"
uuid = "15aa51a1-70ea-45be-ba0e-6b7c05ea5783"
authors = ["Mehmet Hakan Satman <mhsatman@gmail.com>", "Emre Akadal <emreakadal@gmail.com"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
DataFrames = "1"
SQLite = "1"
